/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Luis Sierra
 */
public class Home_Form extends javax.swing.JFrame {

    /**
     * Creates new form Home_Form
     */
    public Home_Form() {
        initComponents();
      
        
         // Cargar la imagen de Home
    ImageIcon originalIcon = new ImageIcon("src\\imagenes\\Home1.png");

    // Escalar la imagen al tamaño del JLabel
    Image image = originalIcon.getImage().getScaledInstance(
        jLabel_BackgroundImage.getWidth(),
        jLabel_BackgroundImage.getHeight(),
        Image.SCALE_SMOOTH // Escalado suave
    );

    // Crear el nuevo ImageIcon con la imagen escalada
    ImageIcon scaledIcon = new ImageIcon(image);

    // Asignar la imagen escalada al JLabel
    jLabel_BackgroundImage.setIcon(scaledIcon);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_BackgroundImage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_AGENDA = new javax.swing.JMenu();
        jMenu1_CITAS = new javax.swing.JMenu();
        jMenuItem1_CRUDCITAS = new javax.swing.JMenuItem();
        jMenu_EMPLEADOS = new javax.swing.JMenu();
        jMenuItem_REGISTRAR_EMPLEADO = new javax.swing.JMenuItem();
        jMenuItemCRUD_EMPLEADO = new javax.swing.JMenuItem();
        jMenu_PACIENTES = new javax.swing.JMenu();
        jMenuItemREGISTRAR_PACIENTE = new javax.swing.JMenuItem();
        jMenuItemCRUD_PACIENTE = new javax.swing.JMenuItem();
        jMenu_USUARIO = new javax.swing.JMenu();
        jMenuItemREGISTRAR_USERS = new javax.swing.JMenuItem();
        jMenuItemCRUD_USERS = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");
        setPreferredSize(new java.awt.Dimension(700, 551));

        jMenu_AGENDA.setBackground(new java.awt.Color(0, 0, 255));
        jMenu_AGENDA.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_AGENDA.setText("AGENDA |");
        jMenu_AGENDA.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenu_AGENDA.setOpaque(true);

        jMenu1_CITAS.setText("CITAS");

        jMenuItem1_CRUDCITAS.setText("CRUD");
        jMenuItem1_CRUDCITAS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1_CRUDCITASMouseClicked(evt);
            }
        });
        jMenuItem1_CRUDCITAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_CRUDCITASActionPerformed(evt);
            }
        });
        jMenu1_CITAS.add(jMenuItem1_CRUDCITAS);

        jMenu_AGENDA.add(jMenu1_CITAS);

        jMenuBar1.add(jMenu_AGENDA);
        jMenu_AGENDA.getAccessibleContext().setAccessibleName("PRODUCTO ");

        jMenu_EMPLEADOS.setBackground(new java.awt.Color(0, 0, 255));
        jMenu_EMPLEADOS.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_EMPLEADOS.setText("EMPLEADOS |");
        jMenu_EMPLEADOS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenu_EMPLEADOS.setOpaque(true);
        jMenu_EMPLEADOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_EMPLEADOSMouseClicked(evt);
            }
        });
        jMenu_EMPLEADOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_EMPLEADOSActionPerformed(evt);
            }
        });

        jMenuItem_REGISTRAR_EMPLEADO.setText("REGISTRAR");
        jMenuItem_REGISTRAR_EMPLEADO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem_REGISTRAR_EMPLEADOMouseClicked(evt);
            }
        });
        jMenuItem_REGISTRAR_EMPLEADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_REGISTRAR_EMPLEADOActionPerformed(evt);
            }
        });
        jMenu_EMPLEADOS.add(jMenuItem_REGISTRAR_EMPLEADO);

        jMenuItemCRUD_EMPLEADO.setText("CRUD");
        jMenuItemCRUD_EMPLEADO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemCRUD_EMPLEADOMouseClicked(evt);
            }
        });
        jMenuItemCRUD_EMPLEADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCRUD_EMPLEADOActionPerformed(evt);
            }
        });
        jMenu_EMPLEADOS.add(jMenuItemCRUD_EMPLEADO);

        jMenuBar1.add(jMenu_EMPLEADOS);

        jMenu_PACIENTES.setBackground(new java.awt.Color(0, 0, 255));
        jMenu_PACIENTES.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_PACIENTES.setText("PACIENTES|");
        jMenu_PACIENTES.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenu_PACIENTES.setOpaque(true);
        jMenu_PACIENTES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_PACIENTESMouseClicked(evt);
            }
        });
        jMenu_PACIENTES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_PACIENTESActionPerformed(evt);
            }
        });

        jMenuItemREGISTRAR_PACIENTE.setText("REGISTRAR");
        jMenuItemREGISTRAR_PACIENTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemREGISTRAR_PACIENTEMouseClicked(evt);
            }
        });
        jMenuItemREGISTRAR_PACIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemREGISTRAR_PACIENTEActionPerformed(evt);
            }
        });
        jMenu_PACIENTES.add(jMenuItemREGISTRAR_PACIENTE);

        jMenuItemCRUD_PACIENTE.setText("CRUD");
        jMenuItemCRUD_PACIENTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemCRUD_PACIENTEMouseClicked(evt);
            }
        });
        jMenuItemCRUD_PACIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCRUD_PACIENTEActionPerformed(evt);
            }
        });
        jMenu_PACIENTES.add(jMenuItemCRUD_PACIENTE);

        jMenuBar1.add(jMenu_PACIENTES);

        jMenu_USUARIO.setBackground(new java.awt.Color(0, 0, 255));
        jMenu_USUARIO.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_USUARIO.setText("USUARIO |");
        jMenu_USUARIO.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenu_USUARIO.setOpaque(true);
        jMenu_USUARIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_USUARIOMouseClicked(evt);
            }
        });
        jMenu_USUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_USUARIOActionPerformed(evt);
            }
        });

        jMenuItemREGISTRAR_USERS.setText("REGISTRAR");
        jMenuItemREGISTRAR_USERS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemREGISTRAR_USERSMouseClicked(evt);
            }
        });
        jMenuItemREGISTRAR_USERS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemREGISTRAR_USERSActionPerformed(evt);
            }
        });
        jMenu_USUARIO.add(jMenuItemREGISTRAR_USERS);

        jMenuItemCRUD_USERS.setText("CRUD");
        jMenuItemCRUD_USERS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemCRUD_USERSMouseClicked(evt);
            }
        });
        jMenuItemCRUD_USERS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCRUD_USERSActionPerformed(evt);
            }
        });
        jMenu_USUARIO.add(jMenuItemCRUD_USERS);

        jMenuBar1.add(jMenu_USUARIO);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_BackgroundImage, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_BackgroundImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_USUARIOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_USUARIOMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu_USUARIOMouseClicked

    private void jMenu_USUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_USUARIOActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jMenu_USUARIOActionPerformed

    private void jMenu_PACIENTESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_PACIENTESActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenu_PACIENTESActionPerformed

    private void jMenu_PACIENTESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_PACIENTESMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu_PACIENTESMouseClicked

    private void jMenu_EMPLEADOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_EMPLEADOSActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu_EMPLEADOSActionPerformed

    private void jMenu_EMPLEADOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_EMPLEADOSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_EMPLEADOSMouseClicked

//Eventos para llamar los fomrularios de registos y crud
    private void jMenuItem1_CRUDCITASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_CRUDCITASActionPerformed
        // TODO add your handling code here:

        Admin_Agenda_Form  agendaForm = new vista.Admin_Agenda_Form();
                agendaForm.pack();
                agendaForm.setVisible(true);
                agendaForm.setLocationRelativeTo(null);
                agendaForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem1_CRUDCITASActionPerformed

    private void jMenuItem1_CRUDCITASMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1_CRUDCITASMouseClicked
        // TODO add your handling code here:
     Admin_Agenda_Form  agendaForm = new vista.Admin_Agenda_Form();
                agendaForm.pack();
                agendaForm.setVisible(true);
                agendaForm.setLocationRelativeTo(null);
                agendaForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem1_CRUDCITASMouseClicked

    private void jMenuItem_REGISTRAR_EMPLEADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_REGISTRAR_EMPLEADOActionPerformed
        // TODO add your handling code here:
        
         vista.Register_Empleado  registerEmpleado = new vista.Register_Empleado ();
                registerEmpleado.pack();
                registerEmpleado.setVisible(true);
                registerEmpleado.setLocationRelativeTo(null);
                registerEmpleado.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        
        
    }//GEN-LAST:event_jMenuItem_REGISTRAR_EMPLEADOActionPerformed

    private void jMenuItem_REGISTRAR_EMPLEADOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem_REGISTRAR_EMPLEADOMouseClicked
        // TODO add your handling code here:
        vista.Register_Empleado  registerEmpleado = new vista.Register_Empleado ();
                registerEmpleado.pack();
                registerEmpleado.setVisible(true);
                registerEmpleado.setLocationRelativeTo(null);
                registerEmpleado.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        
    }//GEN-LAST:event_jMenuItem_REGISTRAR_EMPLEADOMouseClicked

    private void jMenuItemCRUD_EMPLEADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCRUD_EMPLEADOActionPerformed
        // TODO add your handling code here:
         Admin_Empleado_Form  empleadoForm = new vista.Admin_Empleado_Form();
                empleadoForm.pack();
                empleadoForm.setVisible(true);
                empleadoForm.setLocationRelativeTo(null);
                empleadoForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jMenuItemCRUD_EMPLEADOActionPerformed

    private void jMenuItemCRUD_EMPLEADOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCRUD_EMPLEADOMouseClicked
        // TODO add your handling code here:
        Admin_Empleado_Form  empleadoForm = new vista.Admin_Empleado_Form();
                empleadoForm.pack();
                empleadoForm.setVisible(true);
                empleadoForm.setLocationRelativeTo(null);
                empleadoForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        
    }//GEN-LAST:event_jMenuItemCRUD_EMPLEADOMouseClicked

    private void jMenuItemREGISTRAR_PACIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemREGISTRAR_PACIENTEActionPerformed
        // TODO add your handling code here:
           vista.Register_Paciente  registerPaciente = new vista.Register_Paciente();
                registerPaciente.pack();
                registerPaciente.setVisible(true);
                registerPaciente.setLocationRelativeTo(null);
                registerPaciente.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jMenuItemREGISTRAR_PACIENTEActionPerformed

    private void jMenuItemREGISTRAR_PACIENTEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemREGISTRAR_PACIENTEMouseClicked
        // TODO add your handling code here:
         vista.Register_Paciente  registerPaciente = new vista.Register_Paciente();
                registerPaciente.pack();
                registerPaciente.setVisible(true);
                registerPaciente.setLocationRelativeTo(null);
                registerPaciente.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jMenuItemREGISTRAR_PACIENTEMouseClicked

    private void jMenuItemCRUD_PACIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCRUD_PACIENTEActionPerformed
        // TODO add your handling code here:
         vista.Admin_Paciente_Form pacienteForm = new vista.Admin_Paciente_Form();
                pacienteForm.pack();
                //pacienteForm.pack();
                pacienteForm.setVisible(true);
                pacienteForm.setLocationRelativeTo(null);
                pacienteForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jMenuItemCRUD_PACIENTEActionPerformed

    private void jMenuItemCRUD_PACIENTEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCRUD_PACIENTEMouseClicked
        // TODO add your handling code here:
        
         vista.Admin_Paciente_Form pacienteForm = new vista.Admin_Paciente_Form();
                pacienteForm.pack();
                pacienteForm.setVisible(true);
                pacienteForm.setLocationRelativeTo(null);
                pacienteForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemCRUD_PACIENTEMouseClicked

    private void jMenuItemREGISTRAR_USERSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemREGISTRAR_USERSActionPerformed
        // TODO add your handling code here:
        vista.Register_Form  registerUsers = new vista.Register_Form();
                registerUsers.pack();
                registerUsers.setVisible(true);
                registerUsers.setLocationRelativeTo(null);
                registerUsers.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jMenuItemREGISTRAR_USERSActionPerformed

    private void jMenuItemREGISTRAR_USERSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemREGISTRAR_USERSMouseClicked
        // TODO add your handling code here:
        vista.Register_Form  registerUsers = new vista.Register_Form();
                registerUsers.pack();
                registerUsers.setVisible(true);
                registerUsers.setLocationRelativeTo(null);
                registerUsers.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jMenuItemREGISTRAR_USERSMouseClicked

    private void jMenuItemCRUD_USERSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCRUD_USERSActionPerformed
        // TODO add your handling code here:
       vista.Admin_Users_Form userForm = new vista.Admin_Users_Form();
                userForm.pack();
                userForm.setVisible(true);
                userForm.setLocationRelativeTo(null);
                userForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
          
        
        
    }//GEN-LAST:event_jMenuItemCRUD_USERSActionPerformed

    private void jMenuItemCRUD_USERSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCRUD_USERSMouseClicked
        // TODO add your handling code here:
        
         vista.Admin_Users_Form userForm = new vista.Admin_Users_Form();
                userForm.pack();
                userForm.setVisible(true);
                userForm.setLocationRelativeTo(null);
                userForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jMenuItemCRUD_USERSMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel_BackgroundImage;
    public javax.swing.JMenu jMenu1_CITAS;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1_CRUDCITAS;
    private javax.swing.JMenuItem jMenuItemCRUD_EMPLEADO;
    private javax.swing.JMenuItem jMenuItemCRUD_PACIENTE;
    private javax.swing.JMenuItem jMenuItemCRUD_USERS;
    private javax.swing.JMenuItem jMenuItemREGISTRAR_PACIENTE;
    private javax.swing.JMenuItem jMenuItemREGISTRAR_USERS;
    private javax.swing.JMenuItem jMenuItem_REGISTRAR_EMPLEADO;
    private javax.swing.JMenu jMenu_AGENDA;
    private javax.swing.JMenu jMenu_EMPLEADOS;
    private javax.swing.JMenu jMenu_PACIENTES;
    public javax.swing.JMenu jMenu_USUARIO;
    // End of variables declaration//GEN-END:variables
}
